### ISSUE TITLE
Branch is hard coded to main, leading to 404s

### ISSUE THREAD

**Issue by gabek** [contribute-design/contribute.design#52]
**Describe the bug**

The branch for linking to a repository `DESIGN.md` is hard coded to `main` leading to 404s if the repository does not use that as a branch name.

https://github.com/contribute-design/contribute.design/blob/cf38d5c74a06136293ca6a637f0d5692b269aa1a/pages/%5Borg%5D/%5Bproject%5D.tsx#L260

**To Reproduce**

Example: https://contribute.design/owncast/owncast

**Expected behavior**

A branch should not be hard coded to `main`.

**Comment by fivenp** [comment]
Thank you so much for spotting this @gabek 

A fix is being deployed as we speak :)
